name: Docker Image CI

on:
  push:
    branches:
      - FEAT-*
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: raspbian-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
